source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
platform :ios, '12.0'

use_frameworks!

target 'Example' do
end

target 'ExampleTests' do
  pod 'XCTestBeauty', :path => '../'
end
