source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :generate_multiple_pod_projects => true, :warn_for_unused_master_specs_repo => false
platform :ios, '12.0'

use_frameworks!

target 'Example' do
end

target 'ExampleTests' do
  pod 'BeautyTest/XCShortHand', :path => '../'
  pod 'BeautyTest/SnapshotTest', :path => '../'
end
